export const Dada = {
    home: {
        id: 'home1',
        title: 'ДІМ 1',
        flats: [
            {
                address: 'Заповніть данні',
                area: 100,
                calculatorFlat: [
                    {
                        comments: '',
                        currentDataElectricity: 0,
                        currentDataWater: 0,
                        dateCalculator: '16.08.2022',
                        electricityTariff: 1.68,
                        garbageRemovalTariff: 50,
                        id: 'calculatorFlat1',
                        index: 0,
                        messageElectricity: '',
                        messageWater: '',
                        multiplicationElectricity: 0,
                        multiplicationWater: 0,
                        preliminaryDataElectricity: 0,
                        preliminaryDataWater: 0,
                        resultAllCalculate: 0,
                        resultAllUtilityPayments: 0,
                        resultElectricity: 0,
                        resultInternet: 0,
                        resultOtherOptions: 0,
                        resultRent: 0,
                        resultWater: 0,
                        waterTariff: 30.39,
                    },
                ],
                dateEviction: 'Заповніть данні',
                dateSettlement: 'Заповніть данні',
                description: 'Заповніть данні',
                emailOccupant: 'Заповніть данні',
                floor: 1,
                id: 'flat1',
                images: [{ url: 'https://firebasestorage.googleapis.com/v0/b/komunalka-home.appspot.com/o/2142936.png?alt=media&token=20a42143-537a-4217-baac-3a0bd1b3394d' }],
                occupant: 'Заповніть данні',
                owner: 'Заповніть данні',
                ownerEmail: 'Заповніть данні',
                ownerPhone: 'Заповніть данні',
                phoneOccupant: 'Заповніть данні',
                price: 100,
                rooms: 1,
                title: 'КВАРТИРА 1',
                wifiName: 'Заповніть данні',
                wifiPassword: 'Заповніть данні',
            },
        ],
    }
} as const;

export const homeNew = (id: number) => {
    return {
        id: `home${id}`,
        title: `ДІМ ${id}`,
        flats: [
            {
                address: 'Заповніть данні',
                area: 100,
                calculatorFlat: [
                    {
                        comments: '',
                        currentDataElectricity: 0,
                        currentDataWater: 0,
                        dateCalculator: '16.08.2022',
                        electricityTariff: 1.68,
                        garbageRemovalTariff: 50,
                        id: 'calculatorFlat1',
                        index: 0,
                        messageElectricity: '',
                        messageWater: '',
                        multiplicationElectricity: 0,
                        multiplicationWater: 0,
                        preliminaryDataElectricity: 0,
                        preliminaryDataWater: 0,
                        resultAllCalculate: 0,
                        resultAllUtilityPayments: 0,
                        resultElectricity: 0,
                        resultInternet: 0,
                        resultOtherOptions: 0,
                        resultRent: 0,
                        resultWater: 0,
                        waterTariff: 30.39,
                    },
                ],
                dateEviction: 'Заповніть данні',
                dateSettlement: 'Заповніть данні',
                description: 'Заповніть данні',
                emailOccupant: 'Заповніть данні',
                floor: 1,
                id: 'flat1',
                images: [{ url: 'https://firebasestorage.googleapis.com/v0/b/komunalka-home.appspot.com/o/2142936.png?alt=media&token=20a42143-537a-4217-baac-3a0bd1b3394d' }],
                occupant: 'Заповніть данні',
                owner: 'Заповніть данні',
                ownerEmail: 'Заповніть данні',
                ownerPhone: 'Заповніть данні',
                phoneOccupant: 'Заповніть данні',
                price: 100,
                rooms: 1,
                title: 'КВАРТИРА 1',
                wifiName: 'Заповніть данні',
                wifiPassword: 'Заповніть данні',
            },
        ],
    }
}

export const flatNew = (id: number) => {
    return {
        address: 'Заповніть данні',
        area: 100,
        calculatorFlat: [
            {
                comments: '',
                currentDataElectricity: 0,
                currentDataWater: 0,
                dateCalculator: '16.08.2022',
                electricityTariff: 1.68,
                garbageRemovalTariff: 50,
                id: `calculatorFlat${id}`,
                index: id,
                messageElectricity: '',
                messageWater: '',
                multiplicationElectricity: 0,
                multiplicationWater: 0,
                preliminaryDataElectricity: 0,
                preliminaryDataWater: 0,
                resultAllCalculate: 0,
                resultAllUtilityPayments: 0,
                resultElectricity: 0,
                resultInternet: 0,
                resultOtherOptions: 0,
                resultRent: 0,
                resultWater: 0,
                waterTariff: 30.39,
            },
        ],
        dateEviction: 'Заповніть данні',
        dateSettlement: 'Заповніть данні',
        description: 'Заповніть данні',
        emailOccupant: 'Заповніть данні',
        floor: 1,
        id: `flat${id}`,
        images: [{ url: 'https://firebasestorage.googleapis.com/v0/b/komunalka-home.appspot.com/o/2142936.png?alt=media&token=20a42143-537a-4217-baac-3a0bd1b3394d' }],
        occupant: 'Заповніть данні',
        owner: 'Заповніть данні',
        ownerEmail: 'Заповніть данні',
        ownerPhone: 'Заповніть данні',
        phoneOccupant: 'Заповніть данні',
        price: 100,
        rooms: 1,
        title: `КВАРТИРА ${id}`,
        wifiName: 'Заповніть данні',
        wifiPassword: 'Заповніть данні',
    }

}